# Generated by Django 5.2.12 on 2026-04-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maintenanceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolution_action',
            field=models.CharField(choices=[('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='RESOLVED', max_length=20),
        ),
    ]
