# Generated by Django 5.2.12 on 2026-04-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alert_resolution_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
