# Generated by Django 5.2.12 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_maintenanceschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='company_scope',
            field=models.CharField(db_index=True, default='PUBLIC', max_length=150),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='company_scope',
            field=models.CharField(db_index=True, default='PUBLIC', max_length=150),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='company_scope',
            field=models.CharField(db_index=True, default='PUBLIC', max_length=150),
        ),
    ]

